# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MerchanMan
description: a test site for learning jekyll

url: https://github.com/ben-kenobi/MerchanMan
baseurl: "/MerchanMan"
#baseurl: ""

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
plugins_dir:
  - jekyll-feed

gitrepo: MerchanMan

social:
 github: ben-kenobi
 facebook: Bruce Mathers
 email: whatelsecani@gmail.com

google_analytics: "UA-103425024-1"

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      excerpt_separator: <!--more-->

theme: jekyll-theme-cayman
